Siganushka\UserBundle\Entity\User:
    attributes:
        id:
            groups: ['user:item', 'user:collection']
        identifier:
            groups: ['user:item', 'user:collection']
        roles:
            groups: ['user:item', 'user:collection']
        enabled:
            groups: ['user:item', 'user:collection']
        createdAt:
            groups: ['user:item', 'user:collection']
        updatedAt:
            groups: ['user:item', 'user:collection']
